# Generated by Django 5.0.6 on 2024-06-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_createbookreview_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='createbookborrowedhistory',
            name='book_return',
            field=models.BooleanField(default=False),
        ),
    ]
