# Generated by Django 5.0.6 on 2024-06-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_createbookborrowedhistory_book_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcategory',
            name='slgu',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
