# Generated by Django 5.0.6 on 2024-06-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_createcategory_slgu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createcategory',
            old_name='slgu',
            new_name='slug',
        ),
    ]
